"""empty message

Revision ID: c68efaa92766
Revises: 
Create Date: 2018-03-09 22:44:01.302779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68efaa92766'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('creator_uuid', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('city', sa.TEXT(), nullable=False),
    sa.Column('nb_rooms', sa.INTEGER(), nullable=False),
    sa.Column('rooms_description', sa.TEXT(), nullable=True),
    sa.Column('owner', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
